wip: create static assert on struct sizes
Pro: compile time check
Con: It requires to make lot of internal parts public.

This creates the following compile error:

:/build$ make lib/tests/test_persist_state
  CC       lib/tests/test_persist_state-test_persist_state.o
In file included from
/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /source/lib/compat/glib.h:31,
                 from /source/lib/syslog-ng.h:35,
                 from /source/lib/persist-state.h:28,
                 from /source/lib/tests/test_persist_state.c:29:
/usr/include/glib-2.0/glib/gmacros.h:738:31: error: static assertion
failed: "Expression evaluates to false"
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression
evaluates to false")
      |                               ^~~~~~~~~~~~~~
/source/lib/persist-state.h:108:48: note: in expansion of macro
‘G_STATIC_ASSERT’
  108 | #define PERSIST_STATE_SIZE_STATIC_ASSERT(TYPE) G_STATIC_ASSERT(
ROUNDUP(sizeof(TYPE)) + sizeof(PersistValueHeader) <
PERSIST_FILE_WATERMARK)
      |                                                ^~~~~~~~~~~~~~~
/source/lib/tests/test_persist_state.c:46:1: note: in expansion of macro
‘PERSIST_STATE_SIZE_STATIC_ASSERT’
   46 | PERSIST_STATE_SIZE_STATIC_ASSERT(TestState);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:20878:
lib/tests/test_persist_state-test_persist_state.o] Error 1

Signed-off-by: Laszlo Szemere <laszlo.szemere@oneidentity.com>